### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by rzagramonte**

### CODE REVIEW

**Comment by octoshrimpy** [comment]
Could you remove the description of the colors from the cantrip section and add them to the look up table file [here](https://github.com/octoshrimpy/chromaforge/blob/main/look_up_tables/look_up_info_tables.md)?

**Comment by rzagramonte** [comment]
yis

**Comment by rzagramonte** [comment]
Changes made

**Review by octoshrimpy — APPROVED** [review]
these look great!

**Pull request merged**
